name: "hello world"
description: "This is a test action"
inputs:
  message:
    description: "this is a message"
    required: true
outputs:
  time:
    description: "the time when run this action"
    value: ${{ steps.hello.outputs.time }}
runs:
  using: "composite"
  steps:
    - id: hello
      run: ./hello.sh
      shell: bash